version: '3.4'
x-logging:
  driver: json-file
  options:
    max-size: 10m
    max-file: '3'
services:
  unomi-studio:
    container_name: unomi-studio
    image: 'grootan/unomi-studio:1.0.1'
    environment:
      UNOMI_HOST: 'http://unomi:8282'
      UNOMI_USERNAME: karaf
      UNOMI_PASSWORD: karaf
      ELASTIC_HOST: 'http://elasticsearch:9300'
    volumes:
      - './sslcert:/sslcert'
    ports:
      - '8085:8085'
      - '8445:8445'
    depends_on:
      - unomi
      - elasticsearch
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.4.2'
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=contextElasticSearch
    volumes:
      - './data/elasticsearch/:/usr/share/elasticsearch/data'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    restart: always
    ports:
      - '9300:9300'
  unomi:
    image: 'apache/unomi:1.5.6'
    environment:
      - 'UNOMI_ELASTICSEARCH_ADDRESSES=elasticsearch:9300'
    volumes:
      - './data/elasticsearch/:/usr/share/elasticsearch/data'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    restart: always
    ports:
      - '8282:8282'
      - '9444:9444'
      - '8103:8103'
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
